__version__ = '0.1.0'
__author__ = 'Leonoy Douglas'
__email__ = 'leonoy' '@' 'douglas.ca'
__url__ = 'https://github.com/leonoyd/codeviz'
__description__ = 'Generates a call graph from information obtain from GCC compilation process'
